// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// IMPORTANT: Replace these placeholder values with your actual Firebase
/// project configuration. You can get these values from the Firebase Console:
/// 1. Go to Project Settings
/// 2. Scroll down to "Your apps" section
/// 3. Click on the web app (or create one)
/// 4. Copy the configuration values
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9NikjBtZLpcYKcjjE8k43BPn37d8aqIE',
    appId: '1:427159776865:web:d97287145d19360195c420',
    messagingSenderId: '427159776865',
    projectId: 'health-management-df4be',
    authDomain: 'health-management-df4be.firebaseapp.com',
    storageBucket: 'health-management-df4be.firebasestorage.app',
    measurementId: 'G-GCLE2W5LWY',
  );

  // TODO: Replace with your actual Firebase Web configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnXa2IWZFzGOquA2cIMA1TZOk_rrBOKBg',
    appId: '1:427159776865:android:a446d8193d14ad9d95c420',
    messagingSenderId: '427159776865',
    projectId: 'health-management-df4be',
    storageBucket: 'health-management-df4be.firebasestorage.app',
  );

  // TODO: Replace with your actual Firebase Android configuration

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg7t2LZbSwh5Y5MIVyL5l2Xd0p4ysserI',
    appId: '1:427159776865:ios:0bb4dfc317a8a4e395c420',
    messagingSenderId: '427159776865',
    projectId: 'health-management-df4be',
    storageBucket: 'health-management-df4be.firebasestorage.app',
    iosBundleId: 'com.example.hospitalManagement',
  );

  // TODO: Replace with your actual Firebase iOS configuration

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg7t2LZbSwh5Y5MIVyL5l2Xd0p4ysserI',
    appId: '1:427159776865:ios:0bb4dfc317a8a4e395c420',
    messagingSenderId: '427159776865',
    projectId: 'health-management-df4be',
    storageBucket: 'health-management-df4be.firebasestorage.app',
    iosBundleId: 'com.example.hospitalManagement',
  );

  // TODO: Replace with your actual Firebase macOS configuration

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9NikjBtZLpcYKcjjE8k43BPn37d8aqIE',
    appId: '1:427159776865:web:5d7160569696d57295c420',
    messagingSenderId: '427159776865',
    projectId: 'health-management-df4be',
    authDomain: 'health-management-df4be.firebaseapp.com',
    storageBucket: 'health-management-df4be.firebasestorage.app',
    measurementId: 'G-35WJ1STJMS',
  );

  // TODO: Replace with your actual Firebase Windows configuration
}